/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.example.agent;

global java.util.Set controlSet;

/*
rule "Find the highest rank" salience 3
lock-on-active
when
    $max : Number() from accumulate( Agent($score : score),
                    max( $score ))
	$agent : Agent( score == $max)
then
	modify( $agent ){ setRank( 1 ) }
	controlSet.add($agent);
end
*/

rule "Find the Top 3 agents" salience 2
lock-on-active
when
	Agent($max1: score) from accumulate(
		$remainingAgent : Agent( $score : score, $rank : rank),
		init(Agent maxagent = null; int maxscore = 0; ),
		action( if( $score > maxscore) {
			maxagent = $remainingAgent;
			maxscore = $score;
		} ),
		result(maxagent)
	)

	$maxagent1: Agent( score == $max1)

	Agent($max2: score) from accumulate(
		$remainingAgent : Agent( score < $max1, $score : score, $rank : rank),
		init(Agent maxagent = null; int maxscore = 0; ),
		action( if( $score > maxscore) {
			maxagent = $remainingAgent;
			maxscore = $score;
		} ),
		result(maxagent)
	)

	$maxagent2: Agent( score == $max2)

	Agent($max3: score) from accumulate(
		$remainingAgent : Agent( score < $max2, $score : score, $rank : rank),
		init(Agent maxagent = null; int maxscore = 0; ),
		action( if( $score > maxscore) {
			maxagent = $remainingAgent;
			maxscore = $score;
		} ),
		result(maxagent)
	)

	$maxagent3: Agent( score == $max3)

	Agent($max4: score) from accumulate(
		$remainingAgent : Agent( score < $max3, $score : score, $rank : rank),
		init(Agent maxagent = null; int maxscore = 0; ),
		action( if( $score > maxscore) {
			maxagent = $remainingAgent;
			maxscore = $score;
		} ),
		result(maxagent)
	)

	$maxagent4: Agent( score == $max4)
	
then
	modify( $maxagent1 ){ setRank( 1 ) }
	modify( $maxagent2 ){ setRank( 2 ) }
	modify( $maxagent3 ){ setRank( 3 ) }
	modify( $maxagent4 ){ setRank( 4 ) }
	controlSet.add($maxagent1);
	controlSet.add($maxagent2);
	controlSet.add($maxagent3);
	controlSet.add($maxagent4);
end

/*
rule "Find the 3rd highest rank" salience 1
lock-on-active
when
	Agent($max: score) from accumulate(
		$remainingAgent : Agent( rank < 0, $score : score, $rank : rank),
		init(Agent maxagent = null; int maxscore = 0; ),
		action( if( $score > maxscore) {
			maxagent = $remainingAgent;
			maxscore = $score;
		} ),
		result(maxagent)
	)
	
then
	modify( $agent2 ){ setRank( 2 ) }
	controlSet.add($max);
end
*/

/*
rule "Find the 2nd highest rank" salience 2
lock-on-active
no-loop
when
	$remainingAgent : Agent(rank < 0)
    $max : Number() from accumulate( Agent( name == $remainingAgent.name, $score : score, $rank : rank),
                    max( $score ))
	$agent2 : Agent( score == $max, rank < 0)
then
	modify( $agent2 ){ setRank( 2 ) }
	controlSet.add($max);
end
*/
